// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_CAoTlGfOX8lY6OZRi3o2_yQajVPDMU',
    appId: '1:712906820855:web:7f5ecd4707ac6976ac17f2',
    messagingSenderId: '712906820855',
    projectId: 'mental-health-app-f2ce3',
    authDomain: 'mental-health-app-f2ce3.firebaseapp.com',
    storageBucket: 'mental-health-app-f2ce3.firebasestorage.app',
    measurementId: 'G-RDKQY3NYWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuA_rtVRNE971J0WG3ygwsulaQsjW9i9Q',
    appId: '1:712906820855:android:26477bff0806eefcac17f2',
    messagingSenderId: '712906820855',
    projectId: 'mental-health-app-f2ce3',
    storageBucket: 'mental-health-app-f2ce3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbwOvry35Ch-wJn-inejziqJMVgigkUis',
    appId: '1:712906820855:ios:3d93ad20b3779b1cac17f2',
    messagingSenderId: '712906820855',
    projectId: 'mental-health-app-f2ce3',
    storageBucket: 'mental-health-app-f2ce3.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbwOvry35Ch-wJn-inejziqJMVgigkUis',
    appId: '1:712906820855:ios:3d93ad20b3779b1cac17f2',
    messagingSenderId: '712906820855',
    projectId: 'mental-health-app-f2ce3',
    storageBucket: 'mental-health-app-f2ce3.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG_CAoTlGfOX8lY6OZRi3o2_yQajVPDMU',
    appId: '1:712906820855:web:e5dd3c4c65bafae0ac17f2',
    messagingSenderId: '712906820855',
    projectId: 'mental-health-app-f2ce3',
    authDomain: 'mental-health-app-f2ce3.firebaseapp.com',
    storageBucket: 'mental-health-app-f2ce3.firebasestorage.app',
    measurementId: 'G-70N69BPF2R',
  );
}
